.PHONY: clean All

All:
	@echo "----------Building project:[ CodeCrafts - Debug ]----------"
	@$(MAKE) -f  "CodeCrafts.mk"
clean:
	@echo "----------Cleaning project:[ CodeCrafts - Debug ]----------"
	@$(MAKE) -f  "CodeCrafts.mk" clean
